#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays the data sorted by occurrence (desc), then IP (lex desc), then HTTP code (num desc)
awk 'NF >= 9 && $9 ~ /^[1-5][0-9][0-9]$/ {count[$1 " " $9]++} END {for (combo in count) {split(combo, parts, " "); print count[combo], parts[1], parts[2]}}' apache-access.log | sort -k1,1nr -k2,2r -k3,3nr
